"""
ExplainabilityService — wraps explanation generation.

In demo mode: returns heuristic importance scores from MockPredictor.
In model mode: will use GNNExplainer / SHAP over the trained model.

TODO (post-training):
    - Integrate torch_geometric.explain.GNNExplainer
    - Compute SHAP values via shap.DeepExplainer on temporal encoder
    - Return actual gradient-based node/edge attributions
"""

from typing import List
from schemas import GraphSnapshot, ExplanationResult, ForecastResult


class ExplainabilityService:
    """
    Generates explanations for a given forecast.
    Currently delegates to the predictor's built-in explanation method.
    """

    def explain(
        self,
        graph: GraphSnapshot,
        forecast: ForecastResult,
    ) -> ExplanationResult:
        """
        Generate an explanation for the given forecast result.

        In demo mode the explanation is already embedded in the ForecastResult
        by MockPredictor. This service provides a standalone interface for
        when explanations need to be generated separately.

        TODO (model mode):
            from torch_geometric.explain import GNNExplainer
            explainer = GNNExplainer(model, epochs=200)
            node_feat_mask, edge_mask = explainer.explain_graph(data, x, edge_index)
            # Map masks back to original nodes/edges
            # Compute SHAP with shap.DeepExplainer(temporal_model, background_data)
        """
        if forecast.explanation:
            return forecast.explanation

        # Fallback: minimal explanation from forecast data
        from schemas import ImportantNode, ImportantEdge, FeatureImportance
        import uuid

        return ExplanationResult(
            id=str(uuid.uuid4()),
            forecast_id=forecast.id,
            summary=f"Risk forecast of {forecast.current_risk:.0%} generated by {forecast.mode} predictor.",
            important_nodes=[],
            important_edges=[],
            feature_importance=[
                FeatureImportance(
                    feature="Risk Score",
                    value=forecast.current_risk,
                    direction="up",
                    description="Overall graph risk score contributed to the forecast.",
                )
            ],
        )
